apiVersion: apps/v1
kind: Deployment
metadata:
  name: haidneraksupdate 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haidneraksupdate
  template:
    metadata:
      labels:
        app: haidneraksupdate 
    spec:
      containers:
        - name: haidneraksupdate 
          image: mycontainerregistryhaidner.azurecr.io/haidneraksupdate
          ports:
          - containerPort: 8080
