'use strict';

const express = require('express');

const PORT = 8080;
const HOST = '0.0.0.0';

const app = express();
app.get('/', (req, res) => {
  res.send('This message is generated by a program\n that runs in a Docker container in a Azure Kubernetes Service\n');
});

app.get('/api', (req, res) => {
  res.send('API');
});

app.listen(PORT, HOST);
console.log(`Running on http://${HOST}:${PORT}`);