'use strict';

const express = require('express');

const PORT = 8080;
const HOST = '0.0.0.0';

const app = express();
app.get('/', (req, res) => {
  res.send('This message is generated by a program\nthat runs in a Docker container in an Azure Kubernetes Service\n');
});

app.get('/api', (req, res) => {
  res.send('<!DOCTYPE html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n<title>Error</title>\n</head>\n<body>\n<pre>\nThis is the API</pre>\n</body>\n</html>');
});

app.listen(PORT, HOST);
console.log(`Running on http://${HOST}:${PORT}`);